language: android
sudo: required
jdk:
  - oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # in minutes (2 minutes by default)

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

before_script:
  - cd shot-consumer
  - mksdcard -l e 512M sdcard.img
  - echo no | android create avd --force --name shot-test-emulator --target 'android-24' --abi armeabi-v7a --device 'Nexus 4' --sdcard sdcard.img
  - emulator -avd test -skin 768x1280 -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - cd ..

script:
  - ./gradlew checkScalafmtAll build test
  - ./gradlew install
  - cd shot-consumer
  - ./gradlew executeScreenshotTests
