name: "Build, lint, and test"
on: [pull_request, push]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  test:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start emulator
        run: shot-consumer/scripts/start_emulator.sh
      - name: Check code formatting
        run: ./gradlew clean checkScalaFmtAll ktlintCheck
      - name: Shot unit tests
        run: ./gradlew test
      - name: Shot unit tests
        run: ./gradlew :shot-android:connectedCheck
      - name: Build and install Shot
        run: ./gradlew uploadArchives
      - name: Execute screenshot tests for shot-consumer-compose
        run: ./gradlew executeScreenshotTests
        working-directory: shot-consumer-compose
      - name: Execute screenshot tests for shot-consumer
        run: ./gradlew executeScreenshotTests
        working-directory: shot-consumer
      - name: Execute screenshot tests for shot-consumer-flavors green flavor
        run: ./gradlew greenDebugExecuteScreenshotTests
        working-directory: shot-consumer-flavors
      - name: Execute screenshot tests for shot-consumer-flavors blue flavor
        run: ./gradlew blueDebugExecuteScreenshotTests
        working-directory: shot-consumer-flavors


